---
- hosts: all
  become: true
  gather_facts: yes
  pre_tasks:
    - name: setting host facts
      set_fact:
        public_ipv4:  "{{ ansible_eth0.ipv4.address }}"
        private_ipv4: "{{ ansible_eth0.ipv4.address }}"
  vars:
    additional_disks:
      - disk: /dev/sdb
        fstype: ext4
        mount_options: defaults
        mount: /data
    docker_opts: "--registry-mirror=http://repo01:5000 --insecure-registry=repo01:5000"
    docker_registries:
      - host: "https://index.docker.io/v1/"
        auth: "Zmx5MndpbmQ6cHdjNTAycg=="
        email: "fly2wind@gmail.com"
      - host: "http://repo01:5000/"
        auth: "Zmx5MndpbmQ6cHdjNTAycg=="
        email: "fly2wind@gmail.com"
    docker_additonal_directory: /data/docker
    rancher_data_dir: /data/rancher
  roles:
    - common
    - docker

- hosts: repository
  become: true
  gather_facts: no
  vars:
    nexus_data_dir: "/data/lib/nexus"
    nexus_local_users:
      - username: fly2wind
        first_name: Docker
        last_name: User
        email: fly2wind@gmail.com
        password: pwc502r
        roles:
          - nx-admin
  roles:
    - nexus

- hosts: master
  become: true
  gather_facts: no
  roles:
    - rancher
