---
- name: config nexus roles
  uri:
    url: "http://localhost:8081/service/siesta/rest/v1/script/roles/run"
    method: POST
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pass }}"
    force_basic_auth: yes
    headers:
      Content-Type: "text/plain"
    body: "{{ item | to_json }}"
    status_code: 200,204
  with_items: "{{ nexus_roles }}"
