# docker-engine is the default package name
docker_package_name: docker-engine
docker_package_version: "1.12.3-0~{{ ansible_distribution_release }}"

# required
docker_required_packages:
  - ca-certificates
  - apt-transport-https
  - linux-image-extra-{{ ansible_kernel }}
  - linux-image-extra-virtual
  - python-setuptools
