---
# rpm install
docker_rpmpackage: no

# daemon options
docker_opts: --registry-mirror=http://fly2wind.m.alauda.cn

#
# registry
#
# A list of registries. e.g.
# docker_registries:
#   - host: docker.chatid.com
#     auth: path/to/ca.crt
docker_registries: []

#  additonal directory
# docker_additonal_directory:
